library/books/urls.py
from django.urls import path
from . import views

app_name = "books"

urlpatterns = [
    path('', views.books_list, name="list"),
    path('new-book/', views.book_new, name="new-book"),
    path('<int:id>', views.book_page, name="page")
]

library/library/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('about/', views.about),
    path('books/', include('books.urls')),
    path('users/', include('users.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout")
]

library/books/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Address(models.Model):
    country = models.CharField(max_length=75)
    city = models.CharField(max_length=75)
    street = models.CharField(max_length=75)
    house = models.IntegerField()

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    birthday = models.DateTimeField()
    address = models.OneToOneField(Address, on_delete=models.CASCADE, primary_key=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Book(models.Model):
    title = models.CharField(max_length=100)
    pages = models.IntegerField()
    price = models.DecimalField(decimal_places=2, max_digits=10)
    genre = models.CharField(max_length=50)
    year = models.IntegerField()
    image = models.ImageField(blank=True, default='book_default.jpg')
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='books')
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

library/users/models.py
from django.db import models

# Create your models here.

library/books/forms.py
from django import forms
from . import models

class CreateBook(forms.ModelForm):
    class Meta:
        model = models.Book
        fields = ['title', 'pages', 'price', 'genre', 'year', 'author', 'image']

library/books/views.py
from django.shortcuts import render, redirect
from .models import Book
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def books_list(request):
    books = Book.objects.all()
    return render(request, 'books/books_list.html', { 'books': books } )

def book_page(request, id):
    book = Book.objects.get(id=id)
    return render(request, 'books/book_page.html', { 'book': book })

@login_required(login_url="/users/login")
def book_new(request):
    if request.method == "POST":
        form = forms.CreateBook(request.POST, request.FILES)
        if form.is_valid():
            newbook = form.save(commit=False)
            newbook.user = request.user
            newbook.save()
            return redirect("books:list")
    else:
        form = forms.CreateBook()
    return render(request, 'books/book_new.html', { 'form': form })

library/library/views.py
# from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    # return HttpResponse("Hello world! It's main page")
    return render(request, 'home.html')

def about(request):
    # return HttpResponse("My about page.")
    return render(request, 'about.html')

library/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def register_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("books:list")
    else:
        form = UserCreationForm()
    return render(request, "users/register.html", { "form": form })

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect("books:list")
    else:
        form = AuthenticationForm()
    return render(request, 'users/login.html', { 'form': form })

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("/")

library/books/templates/books/book_new.html
{% extends 'layout.html' %}

{% block title %}
    Book create
{% endblock %}

{% block content %}
    <h1>Create new book</h1>
    <form 
    class="form-with-validation"
    method="post"
    action="{% url 'books:new-book' %}"
    enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button class="form-submit">Create book</button>
    </form>
{% endblock %}

library/books/templates/books/book_page.html
{% extends 'layout.html' %}

{% block title %}
    {{ book.title }}
{% endblock %}

{% block content %}
    <div class='book-item-container'>
        <div>
            <img 
                class="book-image"
                src="{{ book.image.url }}" 
                alt="{{ book.title }}"/>
        </div>
        <div>
            <h1>{{ book.title }}</h1>
            <h3>Pages: {{ book.pages }}</h3>
            <h3>Price: {{ book.price }}</h3>
            <h3>Genre: {{ book.genre }}</h3>
            <h3>Year: {{ book.year }}</h3>
            <h3>User: {{ book.user }}</h3>
            <h4>Author: {{ book.author.first_name }} {{ book.author.last_name }}</h4>
            <p><a href="{% url 'books:list' %}">Back</a></p>
        </div>
    </div>

{% endblock %}

library/books/templates/books/books_list.html
{% extends 'layout.html' %}

{% block title %}
    Books list
{% endblock %}

{% block content %}
    <h1>Books list</h1>
    <p>Go to <a href="/">Home</a> page</p>

    <div class="container text-center">
        <div class="row">
            {% for book in books %}
            <div class="col-3 m-5 border border-info-subtle rounded-4" >
                <img 
                    class="books-list-image"
                    src="{{ book.image.url }}"
                    alt="{{ book.title }}" />
                <h2>
                    <a href="{% url 'books:page' id=book.id %}">
                        {{ book.title }}
                    </a>
                </h2>
                <p>{{ book.price }}</p>
                <p>Added by {{ book.user }}</p>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

library/templates/about.html
{% extends "layout.html" %}

{% block title %}
    About
{% endblock %}

{% block content %}
    <h1>About</h1>
    <p>With Django, you can take web applications from concept to launch in a matter of hours. Django takes care of much of the hassle of web development, so you can focus on writing your app without needing to reinvent the wheel. It’s free and open source.</p>
    <p>Go back to <a href="/">main page</a></p>
{% endblock %}

library/templates/home.html
{% extends "layout.html" %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <h1>Home page</h1>
    <p>Welcome on my django project. <a href="/about">About</a></p>
{% endblock %}

library/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/style.css' %}" />
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" defer></script>
        <script src="{% static 'js/main.js' %}" defer></script>
        <title>
            {% block title %}
                Library app
            {% endblock %}
        </title>
    </head>
    <body>
        <nav class="nav-container">
            <div>
                <a href="/">🏠</a> |
                <a href="/about">📔</a> |
                <a href="{% url 'books:list' %}">📚</a> |
                {% if user.is_authenticated %}
                    <a href="{% url 'books:new-book' %}">➕</a> |
                {% endif %}
            </div>
            <div>
                {% if not user.is_authenticated %}
                    <a  
                        class="nav-auth"
                        href="{% url 'users:login' %}">
                    Login</a>
                    <a  
                        class="nav-auth"
                        href="{% url 'users:register' %}">
                    Register</a>
                {% else %}
                    <form class="logout" action="{% url 'users:logout' %}" method="post">
                        {% csrf_token %}
                        <button class="logout-button nav-auth">Logout</button>
                    </form>
                {% endif %}
            </div>    
            
        </nav>
        <main>
            {% block content %}
            {% endblock %}
        </main>
    </body>
</html>

library/users/templates/users/login.html
{% extends 'layout.html' %}

{% block title %}
    Login
{% endblock %}

{% block content %}
    <h1>Login user</h1>
    <form
        class="form-with-validation"
        action="/users/login/"
        method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}"/>
        {% endif %}
        <button class="form-submit">Login</button>
    </form>    

{% endblock %}

library/users/templates/users/register.html
{% extends 'layout.html' %}

{% block title %}
    Register
{% endblock %}

{% block content %}
    <h1>Register new user</h1>
    <form
        class="form-with-validation"
        action="/users/register/"
        method="post">
        {% csrf_token %}
        {{ form }}
        <button class="form-submit">Regiter</button>
    </form>    

{% endblock %}